version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    command: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    expose:
      - "8000"
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:1.25
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    restart: always

