[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements-production.txt"

[deploy]
startCommand = "gunicorn --config deployment/gunicorn_railway_config.py deployment.production_app:application"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
DATABASE_URL = "${{ TURSO_DATABASE_URL }}"
AUTH_TOKEN = "${{ TURSO_AUTH_TOKEN }}"
CLERK_PUBLISHABLE_KEY = "${{ CLERK_PUBLISHABLE_KEY }}"
CLERK_SECRET_KEY = "${{ CLERK_SECRET_KEY }}"
CLERK_WEBHOOK_SECRET = "${{ CLERK_WEBHOOK_SECRET }}"
STRIPE_PUBLISHABLE_KEY = "${{ STRIPE_PUBLISHABLE_KEY }}"
STRIPE_SECRET_KEY = "${{ STRIPE_SECRET_KEY }}"
STRIPE_WEBHOOK_SECRET = "${{ STRIPE_WEBHOOK_SECRET }}"
SECRET_KEY = "${{ SECRET_KEY }}"
FLASK_ENV = "production"
PORT = "${{ PORT }}"